sudo: required
services:
  - docker


before_install:
  - docker build -t hamzawms/react-app -f ./client/Dockerfile.dev ./client


script:
  - docker run hamzawms/react-app npm test -- --coverage


after_success:
  - docker build -t hamzawms/multi-nginx ./nginx
  - docker build -t hamzawms/multi-client ./client
  - docker build -t hamzawms/multi-server ./server
  - docker build -t hamzawms/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push hamzawms/multi-nginx
  - docker push hamzawms/multi-client
  - docker push hamzawms/multi-server
  - docker push hamzawms/multi-worker

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: us-east-1
  app: react-app
  env: React-app-env
  bucket_name: elasticbeanstalk-us-east-1-302263077770
  bucket_path: docker-multi
